### ISSUE TITLE
3.0.0 checklist

### ISSUE THREAD

**Issue by expr** [expr/irc-message#15]
- [x] make sure _irc-prefix-parser_ works as expected (fixing #13)
- [x] rewrite tests
- [x] deprecate _irc-message-stream_, I'm pushing streams now (stream all the things!)
- [x] debug line splitting issue
- [x] manually merge #14
